services:
  app:
    build: .
    container_name: midi_app
    ports:
      - "8090:80"
    env_file: .env
    volumes:
      - midi_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  midi_data:
